### ISSUE TITLE
At Menu "Launch ..." nothing happens

### ISSUE THREAD

**Issue by vlrmprjct** [turbobabr/easyeda-ibom-extension#1]
First of all, Thank you for this useful tool. 

As the description says.
Nothing happens by click on "Launch ...".

**Comment by turbobabr** [comment]
Windows 10 / Edge Chromium 91 - correct? :)

Unfortunately, I'm a `mac` user and don't have a chance to check it atm. Will definitely install some `VM` package in order to check it.

For now, could you check console output for any error messages to see the whole picture?

**Comment by vlrmprjct** [comment]
You are right. I am on WIndows with Edge.
There is no useful log output. I mean there is nothing.

What I have tested is that it works in the web version. 

But not in the desktop version.
Every click on "Launch ..." will create an empty ibom container. Because it can never be closed due to the missing close button.

![image](https://user-images.githubusercontent.com/1859497/111271835-0aa4ee80-8632-11eb-97d6-87f63333b00f.png)

In the next screen I have manipulated the CSS. Now you can see this container.

![image](https://user-images.githubusercontent.com/1859497/111272841-6754d900-8633-11eb-8dfc-bdc3512bccff.png)

In short, the css is missing.

**Comment by turbobabr** [comment]
Am I right that the following style is  just missing?

![image](https://user-images.githubusercontent.com/6356526/111279173-65136e80-8675-11eb-98a7-8f96335ee261.png)

In case it's there - could you try to change `z-index` prop to something else, e.g. `50`

**Comment by turbobabr** [comment]
Please ignore my last comment, I managed to install `VM` and tested the extension with `Edge 89` and apparently it works fine.

I'm not aware of `Edge` beta program / nightly builds, but...
![image](https://user-images.githubusercontent.com/6356526/111290083-c12fc000-8680-11eb-881f-1afa325c017b.png)

Are you a time traveler? :)

**Comment by xsrf** [comment]
I don't have obvious issues in Edge `Edg/89.0.774.54`, Chrome `Chrome/89.0.4389.82` and even the now outdated Desktop-App `EasyEDA/6.4.7 Chrome/69.0.3497.128` on Windows 10.

**Comment by vlrmprjct** [comment]
@turbobabr , there is a misunderstanding.
It works fine on the latest Edge Canary Version. (  yes I come from the future and I come in peace.  🖖🏼  )
But it won't work on the latest EasyEDA Desktop Version , based on Chrome v68.

Maybe it is a local issue.

**Comment by turbobabr** [comment]
@ vlrmprjct, Alright, knowing that it happens in desktop client helped a lot! 😃 

I managed to reproduce the issue:
![image](https://user-images.githubusercontent.com/6356526/111303966-1d4e1080-8690-11eb-8a00-22c379555d15.png)

The root of the problem is that `EasyEdaThemes` you use. It somehow alters global styles and discard `iBom` stuff 🤔  By turning it off - everything works fine.

Will investigate a bit more on this later. Thank you very much for your time! 👏 👏 👏

**Comment by xsrf** [comment]
Oh yeah, I noticed that yesterday with my extensions (and your QR Code one) but haven't had the time to open an issue... He basically removes all styles from the HTML:
https://github.com/FiercestT/EasyEdaThemes/blob/69ec8e27d8b572cf158c9e4dfe45ca06bd0ff413/extension/main.js#L137

**Comment by vlrmprjct** [comment]
Oh yes, @xsrf ,
That is the reason why.

**Comment by turbobabr** [comment]
> Oh yeah, I noticed that yesterday with my extensions (and your QR Code one) but haven't had the time to open an issue... He basically removes all styles from the HTML:
> https://github.com/FiercestT/EasyEdaThemes/blob/69ec8e27d8b572cf158c9e4dfe45ca06bd0ff413/extension/main.js#L137

That’s unfair 🙃 Welcome to the world of truly “hackable” cad systems, where plugins fight with the host and other plugins... ¯\_(ツ)_/¯

Btw, so you guys both use the desktop version?

**Comment by xsrf** [comment]
I use Chrome on W10... Desktop only for testing.

**Comment by turbobabr** [comment]
> I use Chrome on W10... Desktop only for testing.

Cool! I built a dummy ‘live-reload’ set of tools, where a there is a custom chrome extension acts as a glue between EasyEDA, dev-server and source code. It dramatically boosts the productivity of the whole development process, since a developed extensions gets automatically installed on any source file change and there is no need to upload the files manually.

I haven’t published the whole thing because it’s currently platform dependent. I could share the whole thing if you are interested to use it and participate in the adoption to the windows platform.

In case you use Telegram, ping me there - my nickname is “turbobabr” in tg.
